services:
  - type: web
    name: clip-curator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app --timeout 300
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false